import { createContext, useContext, useCallback, ReactNode } from 'react';

export type Language = 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Nav
    'nav.home': 'Início',
    'nav.catalog': 'Catálogo',
    'nav.dresses': 'Maquillaje',
    'nav.sets': 'Skincare',
    'nav.wholesale': 'Atacado',
    'nav.admin': 'Painel Admin',
    'nav.account': 'Minha Conta',
    'nav.login': 'Entrar',
    'nav.promo': 'Promoções',
    'nav.fashion': 'Belleza',
    'nav.blog': 'Blog',

    // Hero
    'hero.badge': '✨ ✨ Novidades em Beleza 2025',
    'hero.title1': 'Elegância que',
    'hero.title2': 'define seu estilo',
    'hero.subtitle': 'Descubra a última tendência em cosméticos e beleza. Peças únicas para cada momento da sua vida.',
    'hero.cta.catalog': 'Ver Catálogo',
    'hero.cta.wholesale': 'Comprar por Atacado',
    'hero.cta.viewProduct': 'Ver Produto',
    'hero.from': 'A partir de',
    'hero.happyClients': 'Clientes felizes',

    // Features
    'features.shipping': 'Envio Express',
    'features.shippingDesc': 'Entrega rápida para todo o Paraguai',
    'features.security': 'Pagamento Seguro',
    'features.securityDesc': 'Transações 100% protegidas',
    'features.returns': 'Trocas Fáceis',
    'features.returnsDesc': '30 dias para trocar seu produto',
    'features.support': 'Suporte 24/7',
    'features.supportDesc': 'Atendimento via WhatsApp',

    // Categories
    'categories.title': 'Explore por Categoria',
    'categories.subtitle': 'Encontre exatamente o que procura nas nossas categorias cuidadosamente selecionadas',
    'categories.products': 'produtos',

    // Featured
    'featured.title': 'Produtos em Destaque',
    'featured.subtitle': 'Os favoritos das nossos clientes',
    'featured.viewAll': 'Ver Tudo',
    'featured.empty': 'Nenhum produto em destaque ainda',

    // AI Assistant
    'ai.title': 'Assistente de Beleza com IA',
    'ai.subtitle': 'Monte listas de compras, tire dúvidas sobre produtos, envios, trocas e muito mais',
    'ai.placeholder': 'Pergunte sobre belleza, produtos, envios, políticas...',
    'ai.welcome': 'Olá! 👋 Sou sua assistente de beleza da Wakai. Posso te ajudar a montar looks, criar listas de compras, tirar dúvidas sobre produtos, envios, políticas de troca e muito mais. Como posso ajudar?',
    'ai.error': 'Desculpe, houve um erro. Tente novamente ou fale conosco pelo WhatsApp.',
    'ai.suggestions.1': '📋 Armar rutina de skincare',
    'ai.suggestions.2': '💄 Sugerir rutina de belleza',
    'ai.suggestions.3': '🚚 Info sobre envios',
    'ai.suggestions.4': '🔄 Política de trocas',

    // Video Reels
    'reels.title': 'Nossos Reels',
    'reels.subtitle': 'Veja nossas últimas tendências em vídeo',

    // B2B
    'b2b.badge': '🏪 Para Revendedores',
    'b2b.title': 'Junte-se à Nossa Rede Atacadista',
    'b2b.subtitle': 'Acesse preços exclusivos, packs especiais a partir de 3 peças, e material de apoio para impulsionar seu negócio.',
    'b2b.cta': 'Solicitar Acesso Atacadista',
    'b2b.catalog': 'Ver Catálogo B2B',

    // New Arrivals
    'arrivals.title': 'Novas Chegadas',
    'arrivals.subtitle': 'As últimos produtos da nossa coleção',
    'arrivals.empty': 'Nenhum produto disponível',
    'arrivals.viewAll': 'Ver Catálogo Completo',

    // FAQ
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Encontre respostas para as dúvidas mais comuns',
    'faq.q1': 'Como funciona o envio?',
    'faq.a1': 'Realizamos envios para todo o Paraguai. Pedidos acima de ₲ 500.000 têm frete grátis. O prazo de entrega é de 2 a 5 dias úteis dependendo da localidade.',
    'faq.q2': 'Qual a política de trocas?',
    'faq.a2': 'Você tem 30 dias para solicitar a troca do produto. O item deve estar sem uso, com etiquetas e embalagem original. Entre em contato pelo WhatsApp para iniciar o processo.',
    'faq.q3': 'Qual a validade dos produtos?',
    'faq.a3': 'Cada produto possui uma informação de validade na página de detalhes. Se tiver dúvidas, nosso assistente de IA ou equipe de atendimento pode te ajudar a escolher o produto ideal.',
    'faq.q4': 'O pagamento é seguro?',
    'faq.a4': 'Sim! Utilizamos criptografia de ponta a ponta em todas as transações. Aceitamos cartões de crédito, débito, transferência bancária e pagamento na entrega.',
    'faq.q5': 'Como funciona o atacado?',
    'faq.a5': 'Para compras no atacado, o pedido mínimo é de 3 unidades por producto. Oferecemos preços especiais e condições exclusivas. Acesse nossa página de atacado para mais informações.',
    'faq.q6': 'Qual a política de privacidade?',
    'faq.a6': 'Seus dados pessoais são protegidos e utilizados apenas para processar pedidos e melhorar sua experiência. Nunca compartilhamos suas informações com terceiros sem seu consentimento.',
    'faq.needHelp': 'Precisa de mais ajuda?',
    'faq.needHelpDesc': 'Nossa equipe está pronta para te ajudar pelo WhatsApp ou através do nosso chat.',
    'faq.viewCatalog': 'Ver Catálogo',
    'faq.wholesalePurchases': 'Compras no Atacado',

    // Cart
    'cart.empty.title': 'Seu carrinho está vazio',
    'cart.empty.subtitle': 'Explore nossa coleção e encontre as produtos perfeitos para você.',
    'cart.empty.cta': 'Ver Catálogo',
    'cart.title': 'Seu Carrinho',
    'cart.size': 'Variante',
    'cart.clear': 'Esvaziar Carrinho',
    'cart.summary': 'Resumo do Pedido',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Frete',
    'cart.shippingCalc': 'Calculado no checkout',
    'cart.total': 'Total',
    'cart.checkout': 'Prosseguir para o Pagamento',
    'cart.freeShipping': 'Frete grátis em compras acima de ₲ 500.000',
    'cart.secure': '🔒 Pagamento 100% seguro com criptografia SSL',

    // Catalog
    'catalog.title': 'Catálogo Completo',
    'catalog.subtitle': 'Explore nossa coleção de cosméticos e beleza com as últimas tendências',
    'catalog.sortNewest': 'Mais Recentes',
    'catalog.sortPriceAsc': 'Preço: Menor para Maior',
    'catalog.sortPriceDesc': 'Preço: Maior para Menor',
    'catalog.sortPopular': 'Mais Populares',
    'catalog.filters': 'Filtros',
    'catalog.searchPlaceholder': 'Buscar produtos...',
    'catalog.products': 'produtos',
    'catalog.noResults': 'Nenhum produto encontrado',
    'catalog.noResultsFor': 'para',
    'catalog.noResultsFilters': 'com os filtros selecionados',
    'catalog.clearFilters': 'Limpar Filtros',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.backToCart': 'Voltar ao carrinho',
    'checkout.contactInfo': 'Informações de Contato',
    'checkout.fullName': 'Nome Completo *',
    'checkout.namePlaceholder': 'Seu nome',
    'checkout.phone': 'Telefone *',
    'checkout.email': 'Email *',
    'checkout.shippingTitle': 'Endereço de Envio',
    'checkout.fullAddress': 'Endereço Completo *',
    'checkout.addressPlaceholder': 'Rua, número, bairro, referências...',
    'checkout.city': 'Cidade *',
    'checkout.cityPlaceholder': 'Assunção, Ciudad del Este...',
    'checkout.notes': 'Observações (opcional)',
    'checkout.notesPlaceholder': 'Instruções especiais de entrega...',
    'checkout.paymentMethod': 'Método de Pagamento',
    'checkout.bankTransfer': 'Transferência Bancária',
    'checkout.bankTransferDesc': 'Receba os dados para transferência após a confirmação',
    'checkout.cashOnDelivery': 'Pagamento na Entrega',
    'checkout.cashOnDeliveryDesc': 'Pague em dinheiro ao receber seu pedido',
    'checkout.cardPayment': 'Cartão de Crédito/Débito',
    'checkout.cardComingSoon': 'Em breve disponível',
    'checkout.orderSummary': 'Resumo do Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Frete',
    'checkout.shippingFree': 'Grátis',
    'checkout.total': 'Total',
    'checkout.placeOrder': 'Finalizar Pedido',
    'checkout.processing': 'Processando...',
    'checkout.freeShippingNote': 'Frete grátis em compras acima de ₲ 500.000',
    'checkout.securePayment': '🔒 Pagamento 100% seguro',
    'checkout.orderConfirmed': 'Pedido Confirmado!',
    'checkout.orderNumberLabel': 'Seu número de pedido é:',
    'checkout.transferDetails': 'Dados para Transferência',
    'checkout.sendReceipt': 'Envie o comprovante pelo WhatsApp para confirmar seu pedido.',
    'checkout.continueShopping': 'Continuar Comprando',
    'checkout.viewOrders': 'Ver Meus Pedidos',
    'checkout.orderCreated': 'Pedido criado!',
    'checkout.orderCreatedDesc': 'Seu número de pedido é',
    'checkout.error': 'Não foi possível criar o pedido',
    'checkout.nameRequired': 'Nome obrigatório',
    'checkout.invalidEmail': 'Email inválido',
    'checkout.phoneRequired': 'Telefone obrigatório',
    'checkout.addressRequired': 'Endereço obrigatório',
    'checkout.cityRequired': 'Cidade obrigatória',
    'checkout.dataProtected': '🔒 Seus dados estão protegidos',
    'checkout.bank': 'Banco',
    'checkout.holder': 'Titular',
    'checkout.accountNumber': 'Conta',
    'checkout.amount': 'Valor',

    // Product Detail
    'product.notFound': 'Produto não encontrado',
    'product.backToCatalog': 'Voltar ao Catálogo',
    'product.new': 'Novo',
    'product.topSeller': 'Mais Vendido',
    'product.color': 'Cor',
    'product.selectLabel': 'Selecione',
    'product.size': 'Variante',
    'product.quantity': 'Quantidade',
    'product.addToCart': 'Adicionar ao Carrinho',
    'product.buyNow': 'Comprar Agora',
    'product.selectSizeAlert': 'Selecione um variante',
    'product.selectSizeDesc': 'Por favor, escolha um variante antes de adicionar ao carrinho.',
    'product.selectColorAlert': 'Selecione uma cor',
    'product.selectColorDesc': 'Por favor, escolha uma cor antes de adicionar ao carrinho.',
    'product.addedToCart': 'Adicionado ao carrinho!',
    'product.addedDesc': 'foi adicionado.',
    'product.expressShipping': 'Envio Express',
    'product.securePayment': 'Pagamento Seguro',
    'product.returnsPolicy': '30 dias troca',
    'product.description': 'Descrição',
    'product.details': 'Detalhes',
    'product.shippingTab': 'Envio',
    'product.descriptionText': 'Este produto é formulado com ingredientes de alta qualidade, projetado para oferecer resultados e cuidado em qualquer ocasião. Perfeita para complementar sua rotina de beleza.',
    'product.material': 'Tipo: Produto dermatologicamente testado',
    'product.cut': 'Uso: Aplicação diária recomendada',
    'product.care': 'Cuidados: Armazenar em local fresco e seco',
    'product.origin': 'Origem: Original de marca',
    'product.expressDetail': 'Envio Express: 2-3 dias úteis para Assunção e Grande Assunção.',
    'product.regularShipping': 'Envio Regular: 5-7 dias úteis para o interior do país.',
    'product.freeShipping': 'Envio Grátis: Em compras acima de ₲ 500.000.',
    'product.related': 'Produtos Relacionados',
    'product.videoTitle': 'Vídeo do Produto',
    'product.wholesalePrice': 'Preço Atacadista',
    'product.perUnit': 'c/u',
    'product.minPieces': 'mín.',
    'product.pieces': 'peças',
    'product.add': 'Adicionar',

    // Auth
    'auth.backToStore': 'Voltar à loja',
    'auth.signIn': 'Entrar',
    'auth.createAccount': 'Criar Conta',
    'auth.signInSubtitle': 'Insira seus dados para acessar sua conta',
    'auth.createAccountSubtitle': 'Junte-se à Wakai e descubra nossa coleção',
    'auth.fullName': 'Nome completo',
    'auth.namePlaceholder': 'Seu nome',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.forgotPassword': 'Esqueci minha senha',
    'auth.loading': 'Carregando...',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'auth.register': 'Cadastre-se',
    'auth.login': 'Faça login',
    'auth.heroTitle': 'Beleza que define seu estilo',
    'auth.heroSubtitle': 'Descubra as últimas tendências em cosméticos e beleza',
    'auth.invalidCredentials': 'Email ou senha incorretos',
    'auth.authError': 'Erro de autenticação',
    'auth.welcome': 'Bem-vindo!',
    'auth.welcomeDesc': 'Login realizado com sucesso',
    'auth.alreadyRegistered': 'Usuário existente',
    'auth.alreadyRegisteredDesc': 'Este email já está registrado. Tente fazer login.',
    'auth.accountCreated': 'Conta criada!',
    'auth.accountCreatedDesc': 'Sua conta foi criada com sucesso',
    'auth.unexpectedError': 'Ocorreu um erro inesperado',
    'auth.attention': 'Atenção',
    'auth.enterEmailFirst': 'Informe seu email primeiro',
    'auth.emailSent': 'Email enviado!',
    'auth.checkEmail': 'Verifique seu email para redefinir sua senha',
    'auth.invalidEmail': 'Email inválido',
    'auth.passwordMin': 'A senha deve ter pelo menos 6 caracteres',
    'auth.nameMin': 'Nome deve ter pelo menos 2 caracteres',
    'auth.passwordMismatch': 'As senhas não coincidem',

    // Account
    'account.title': 'Minha Conta',
    'account.adminPanel': 'Painel Admin',
    'account.signOut': 'Sair',
    'account.signOutToast': 'Sessão encerrada',
    'account.signOutDesc': 'Você saiu com sucesso',
    'account.profile': 'Perfil',
    'account.orders': 'Pedidos',
    'account.addresses': 'Endereços',

    // Promocoes
    'promo.seoTitle': 'Promoções de Beleza | Wakai',
    'promo.seoDesc': 'Aproveite as melhores promoções de cosméticos e beleza. Descontos imperdíveis em maquiagens, cremes, perfumes e muito mais.',
    'promo.title': 'Promoção de Beleza 💄',
    'promo.subtitle': 'Até 40% de desconto em produtos selecionados',
    'promo.description': 'Renove seu coleção de beleza com as melhores ofertas da temporada. Produtos exclusivos com preços imperdíveis por tempo limitado.',
    'promo.limitedOffer': 'Oferta por Tempo Limitado',
    'promo.off': 'Até 40% OFF',
    'promo.offDesc': 'Em produtos selecionados',
    'promo.freeShipping': 'Frete Grátis',
    'promo.freeShippingDesc': 'Nas compras acima de ₲500.000',
    'promo.coupon': 'Cupom BELEZA10',
    'promo.couponDesc': '10% extra na primeira compra',
    'promo.featuredProducts': 'Produtos em Destaque',
    'promo.viewMore': 'Ver mais ofertas',
    'promo.noPromos': 'Nenhuma promoção ativa no momento.',
    'promo.exploreCatalog': 'Explorar Catálogo',
    'promo.ctaTitle': 'Não perca as melhores ofertas!',
    'promo.ctaSubtitle': 'Cadastre-se para receber as promoções exclusivas diretamente no seu WhatsApp.',
    'promo.ctaButton': 'Criar minha conta',

    // Wholesale
    'wholesale.badge': '🏪 Programa Atacadista',
    'wholesale.title': 'Faça seu negócio crescer com a Wakai',
    'wholesale.subtitle': 'Junte-se à nossa rede de revendedores e acesse preços exclusivos, packs flexíveis e todo o apoio que precisa para ter sucesso.',
    'wholesale.requestAccess': 'Solicitar Acesso',
    'wholesale.viewCatalog': 'Ver Catálogo B2B',
    'wholesale.benefitsTitle': 'Benefícios Exclusivos',
    'wholesale.benefitsSubtitle': 'Tudo o que você precisa para impulsionar seu negócio de belleza',
    'wholesale.exclusivePrices': 'Preços Exclusivos',
    'wholesale.exclusivePricesDesc': 'Até 40% de desconto nos preços de atacado',
    'wholesale.flexiblePacks': 'Packs Flexíveis',
    'wholesale.flexiblePacksDesc': 'A partir de 3 unidades por producto, misture cores e variantes',
    'wholesale.training': 'Capacitação',
    'wholesale.trainingDesc': 'Acesso a material de vendas e dicas de negócio',
    'wholesale.vipSupport': 'Suporte VIP',
    'wholesale.vipSupportDesc': 'Atendimento prioritário via WhatsApp',
    'wholesale.pricingTitle': 'Níveis de Preço',
    'wholesale.pricingSubtitle': 'Quanto mais comprar, mais economiza',
    'wholesale.starterPack': 'Pack Inicial',
    'wholesale.businessPack': 'Pack Negócio',
    'wholesale.proPack': 'Pack Pro',
    'wholesale.mostPopular': 'Mais Popular',
    'wholesale.overRetail': 'sobre preço de varejo',
    'wholesale.availableProducts': 'Produtos Disponíveis',
    'wholesale.catalogPreview': 'Prévia do nosso catálogo atacadista',
    'wholesale.viewFullCatalog': 'Ver Catálogo Completo',
    'wholesale.requestAccessTitle': 'Solicite seu Acesso Atacadista',
    'wholesale.requestAccessSubtitle': 'Preencha o formulário e entraremos em contato com você',
    'wholesale.fullName': 'Nome Completo',
    'wholesale.businessName': 'Nome do Negócio',
    'wholesale.businessPlaceholder': 'Sua loja ou marca',
    'wholesale.whatsapp': 'WhatsApp',
    'wholesale.city': 'Cidade',
    'wholesale.howSell': 'Como você vende atualmente?',
    'wholesale.physicalStore': 'Loja física',
    'wholesale.submitRequest': 'Enviar Solicitação',
    'wholesale.responseTime': 'Responderemos em no máximo 24 horas úteis',
    'wholesale.faqTitle': 'Perguntas Frequentes',
    'wholesale.faq1q': 'Qual o pedido mínimo?',
    'wholesale.faq1a': 'O pedido mínimo é de 3 peças do mesmo modelo, podendo misturar cores e variantes.',
    'wholesale.faq2q': 'Como realizo o pagamento?',
    'wholesale.faq2a': 'Aceitamos transferências bancárias, pagamentos com cartão e pagamentos em dinheiro no nosso local.',
    'wholesale.faq3q': 'Quanto tempo leva o envio?',
    'wholesale.faq3a': 'Envios para Assunção em 2-3 dias úteis. Interior do país 5-7 dias úteis.',
    'wholesale.pieces': 'peças',

    // Landing Moda
    'landing.heroTitle': 'Sua Beleza, Seu Poder ✨',
    'landing.heroSubtitle': 'A cosméticos e beleza que te faz brilhar. Vestidos, conjuntos e blusas com qualidade premium e preços acessíveis.',
    'landing.wantToKnow': 'Quero Saber Mais',
    'landing.whyChoose': 'Por que escolher a Wakai?',
    'landing.benefit1': 'Envios para todo o Paraguai',
    'landing.benefit2': 'Preços de atacado a partir de 6 unidades',
    'landing.benefit3': 'Qualidade garantida',
    'landing.benefit4': 'Mais de 5.000 clientes satisfeitas',
    'landing.benefit5': 'Devolução grátis em 7 dias',
    'landing.benefit6': 'Atendimento personalizado via WhatsApp',
    'landing.testimonials': 'O que dizem nossos clientes',
    'landing.testimonial1': 'A melhor loja de cosméticos e beleza. Qualidade incrível e envio rápido.',
    'landing.testimonial2': 'Comprei no atacado e os preços são imbatíveis. Super recomendo!',
    'landing.testimonial3': 'Vestidos lindos, tecido de qualidade. Já sou cliente fixa.',
    'landing.formTitle': 'Receba ofertas exclusivas!',
    'landing.formSubtitle': 'Deixe seus dados e entraremos em contato com os melhores preços.',
    'landing.namePlaceholder': 'Seu nome *',
    'landing.phonePlaceholder': 'Seu telefone / WhatsApp *',
    'landing.emailPlaceholder': 'Seu email (opcional)',
    'landing.sending': 'Enviando...',
    'landing.wantOffers': 'Quero Receber Ofertas',
    'landing.privacyNote': 'Não compartilhamos seus dados. Política de privacidade.',
    'landing.shippingAll': 'Envios para todo PY',
    'landing.securePurchase': 'Compra segura',
    'landing.clients5000': '+5000 clientes',
    'landing.readyTitle': 'Pronto para renovar sua beleza?',
    'landing.viewCatalog': 'Ver Catálogo',
    'landing.talkWhatsApp': 'Falar pelo WhatsApp',
    'landing.formSuccess': 'Obrigada! Entraremos em contato em breve.',
    'landing.formError': 'Erro ao enviar. Tente novamente.',
    'landing.formValidation': 'Por favor, preencha seu nome e telefone.',

    // Footer
    'footer.newsletter.title': 'Junte-se à nossa comunidade',
    'footer.newsletter.subtitle': 'Receba ofertas exclusivas e novidades de belleza',
    'footer.newsletter.placeholder': 'Seu email',
    'footer.newsletter.button': 'Inscrever',
    'footer.brand.desc': 'Seu destino de cosméticos e beleza no Paraguai. Qualidade, estilo e preços incríveis.',
    'footer.shop': 'Loja',
    'footer.company': 'Empresa',
    'footer.help': 'Ajuda',
    'footer.about': 'Sobre Nós',
    'footer.blog': 'Blog',
    'footer.contact': 'Contato',
    'footer.faq': 'FAQ',
    'footer.shipping': 'Envios',
    'footer.returns': 'Devoluções',
    'footer.sizeGuide': 'Guia de Uso',
    'footer.rights': '© 2025 Wakai. Todos os direitos reservados.',
    'footer.privacy': 'Privacidade',
    'footer.terms': 'Termos',
    'footer.blouses': 'Perfumería',
    'footer.pants': 'Skincare',
    'footer.fashionPY': 'Cosméticos no Paraguai',
    'footer.fashionBR': 'Cosméticos no Brasil',
    'footer.fashionIn': 'Cosméticos em',

    // Marketplaces
    'mk.dashboard': 'Marketplaces',
    'mk.dashboard.subtitle': 'Painel de integrações omnichannel',
    'mk.connections': 'Conexões',
    'mk.connections.active': 'Conexões Ativas',
    'mk.catalog': 'Catálogo Marketplace',
    'mk.orders': 'Pedidos Marketplace',
    'mk.stock': 'Estoque Marketplace',
    'mk.logs': 'Logs de Sincronização',
    'mk.messages': 'Central de Mensagens',
    'mk.mapped': 'Produtos Mapeados',
    'mk.imported': 'Pedidos Importados',
    'mk.syncErrors': 'Erros de Sync',
    'mk.recentSync': 'Últimas Sincronizações',
    'mk.noRecentSync': 'Nenhuma sincronização recente.',
    'mk.status': 'Status dos Marketplaces',
    'mk.disconnected': 'Desconectado',
    'mk.connected': 'Conectado',
    'mk.connect': 'Conectar Marketplace',
    'mk.noConnections': 'Nenhum marketplace conectado ainda.',
    'mk.since': 'Desde',
    'mk.syncAll': 'Sincronizar Tudo',
    'mk.searchProduct': 'Buscar produto...',
    'mk.product': 'Produto',
    'mk.price': 'Preço',
    'mk.stockCol': 'Estoque',
    'mk.noOrders': 'Nenhum pedido importado ainda.',
    'mk.externalId': 'ID Externo',
    'mk.marketplace': 'Marketplace',
    'mk.customer': 'Cliente',
    'mk.total': 'Total',
    'mk.statusCol': 'Status',
    'mk.date': 'Data',
    'mk.all': 'Todos',
    'mk.syncedProducts': 'Produtos Sincronizados',
    'mk.lowStock': 'Estoque Baixo',
    'mk.noStock': 'Sem Estoque',
    'mk.localStock': 'Estoque Local',
    'mk.noLogs': 'Nenhum log de sincronização.',
    'mk.operation': 'Operação',
    'mk.error': 'Erro',
    'mk.action': 'Ação',
    'mk.success': 'Sucesso',
    'mk.fail': 'Falha',
    'mk.pending': 'Pendente',
    'mk.token': 'Token / API Key',
    'mk.pasteToken': 'Cole seu token aqui',
    'mk.select': 'Selecione',
    'mk.filter': 'Filtrar',
    'mk.msgCenter': 'Central de Mensagens',
    'mk.msgCenter.subtitle': 'Mensagens dos marketplaces centralizadas',
    'mk.noMessages': 'Nenhuma mensagem recebida.',
    'mk.autoRespond': 'Resposta IA',
    'mk.postSale': 'Pós-Venda',
    'mk.postSaleAutomation': 'Automação Pós-Venda',
    'mk.postSaleAutomation.subtitle': 'Mensagens automáticas de acompanhamento e pesquisa de satisfação',
    'mk.analytics': 'Analytics Marketplace',
    'mk.analytics.subtitle': 'Relatórios de vendas, conversão e performance por canal',
    'mk.totalRevenue': 'Receita Total',
    'mk.totalOrdersMk': 'Total Pedidos',
    'mk.avgTicket': 'Ticket Médio',
    'mk.channels': 'Canais Ativos',
    'mk.salesTrend': 'Tendência de Vendas',
    'mk.ordersByChannel': 'Pedidos por Canal',
    'mk.syncPerformance': 'Performance de Sincronização',
    'mk.noData': 'Sem dados no período selecionado.',
    'mk.today': 'Hoje',
    'mk.days': 'dias',
    'mk.automations': 'Automações',
    'mk.automations.subtitle': 'Integre com n8n, Make e FiqOn via webhooks',
    'mk.addAutomation': 'Nova Automação',
    'mk.newAutomation': 'Configurar Nova Automação',
    'mk.platform': 'Plataforma',
    'mk.triggerEvent': 'Evento Gatilho',
    'mk.ruleName': 'Nome da Regra',
    'mk.save': 'Salvar',
    'mk.cancel': 'Cancelar',
    'mk.rules': 'regras',
    'mk.activeRules': 'ativas',
    'mk.configuredRules': 'Regras Configuradas',
    'mk.noAutomations': 'Nenhuma automação configurada.',
    'mk.replied': 'Respondida',
    'mk.totalMsg': 'Total Mensagens',
    'mk.reply': 'Resposta',
    'mk.typeReply': 'Digite sua resposta...',
    'mk.send': 'Enviar',
    'mk.replySent': 'Resposta enviada!',
    'mk.noSuggestion': 'Sem sugestão disponível',
    'mk.retryOk': 'Retry OK',
    'mk.retry': 'Retry',
    'mk.msgSent': 'Mensagens Enviadas',
    'mk.responseRate': 'Taxa de Resposta',
    'mk.avgSatisfaction': 'Satisfação Média',
    'mk.reviewsObtained': 'Avaliações Obtidas',
    'mk.followUp': 'Acompanhamento',
    'mk.satisfaction': 'Satisfação',
    'mk.reviewRequest': 'Avaliação',
    'mk.crossSell': 'Cross-sell',
    'mk.afterDelivery': 'após entrega',
    'mk.dayAfterDelivery': 'dia após entrega',
    'mk.daysAfterDelivery': 'dias após entrega',
    'mk.hourAfterDelivery': 'h após entrega',
    'mk.edit': 'Editar',
    'mk.automationUpdated': 'Automação atualizada!',
    'mk.ruleSaved': 'Regra salva com sucesso!',
    'mk.editRule': 'Editar Regra',
    'mk.configTriggerTime': 'Configure o template e o tempo de disparo',
    'mk.name': 'Nome',
    'mk.delayHours': 'Atraso (horas)',
    'mk.messageTemplate': 'Template da Mensagem',
    'mk.variables': 'Variáveis',
    'mk.activeCount': 'ativa',
    'mk.activeCountPlural': 'ativas',
    'mk.newAutomationBtn': 'Nova Automação',
    'mk.myAutomations': 'Minhas Automações',
    'mk.readyTemplates': 'Templates Prontos',
    'mk.nodeLibrary': 'Biblioteca de Nós',
    'mk.executionLogs': 'Logs de Execução',
    'mk.metrics': 'Métricas',
    'mk.editor': 'Editor',
    'mk.flows': 'fluxos',
    'mk.activeFlows': 'ativos',
    'mk.noAutomationsCreated': 'Nenhuma automação criada',
    'mk.startWithTemplate': 'Comece com um template pronto ou crie do zero',
    'mk.viewTemplates': 'Ver Templates',
    'mk.draft': 'Rascunho',
    'mk.nodes': 'nós',
    'mk.createdOn': 'Criado em',
    'mk.lastExecution': 'Última execução',
    'mk.templateLoaded': 'Template carregado! Configure e salve.',
    'mk.giveNameToAutomation': 'Dê um nome à automação',
    'mk.addAtLeastOneNode': 'Adicione pelo menos um nó',
    'mk.automationSavedDB': 'Automação salva no banco de dados!',
    'mk.automationRemoved': 'Automação removida',
    'mk.automationDuplicated': 'Automação duplicada',
    'mk.testingAutomation': 'Testando automação...',
    'mk.testError': 'Erro ao testar',
    'mk.testExecuted': 'Teste executado! Verifique os logs.',
    'mk.jsonCopied': 'JSON copiado! Cole no seu',
    'mk.readyTemplatesDesc': 'Templates prontos com nós pré-configurados. Escolha, personalize e ative.',
    'mk.useTemplate': 'Usar Template',
    'mk.allNodesDesc': 'Todos os nós disponíveis para construir suas automações.',
    'mk.executionHistory': 'Histórico de execuções das automações com status de sucesso/falha.',
    'mk.refresh': 'Atualizar',
    'mk.noExecutions': 'Nenhuma execução registrada',
    'mk.executionsWillAppear': 'As execuções aparecerão aqui quando suas automações forem disparadas',
    'mk.automation': 'Automação',
    'mk.event': 'Evento',
    'mk.start': 'Início',
    'mk.duration': 'Duração',
    'mk.successBadge': '✓ Sucesso',
    'mk.failBadge': '✗ Falha',
    'mk.runningBadge': '⟳ Executando',
    'mk.flowRemoved': 'Fluxo removido',
    'mk.automationName': 'Nome da Automação',
    'mk.webhookUrl': 'Webhook URL',
    'mk.flow': 'Fluxo',
    'mk.addNode': 'Adicionar Nó',
    'mk.addNodesToFlow': 'Adicione nós para construir seu fluxo',
    'mk.addFirstNode': 'Adicionar Primeiro Nó',
    'mk.remove': 'Remover',
    'mk.exportJson': 'Exportar JSON',
    'mk.saveAutomation': 'Salvar Automação',

    // Countdown
    'countdown.days': 'Dias',
    'countdown.hours': 'Horas',
    'countdown.minutes': 'Min',
    'countdown.seconds': 'Seg',

    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.dashboardSubtitle': 'Resumo geral da sua loja',
    'admin.totalRevenue': 'Receita Total',
    'admin.orders': 'Pedidos',
    'admin.products': 'Produtos',
    'admin.customers': 'Clientes',
    'admin.pendingOrders': 'pendentes',
    'admin.activeProducts': 'produtos ativos',
    'admin.registered': 'registrados',
    'admin.salesLast7': 'Vendas - Últimos 7 dias',
    'admin.salesLast7Desc': 'Receita e quantidade de pedidos por dia',
    'admin.ordersByStatus': 'Pedidos por Status',
    'admin.leadsByStatus': 'Leads por Status',
    'admin.postsByPlatform': 'Posts por Plataforma',
    'admin.noOrders': 'Sem pedidos',
    'admin.noLeads': 'Sem leads',
    'admin.noPosts': 'Sem posts agendados',
    'admin.recentOrders': 'Pedidos Recentes',
    'admin.recentOrdersDesc': 'Os últimos 5 pedidos realizados',
    'admin.noOrdersYet': 'Nenhum pedido ainda',
    'admin.revenue': 'Receita',
    'admin.ordersLabel': 'Pedidos',
    'admin.scheduled': 'Agendados',
    'admin.published': 'Publicados',
    'admin.statusPending': 'Pendente',
    'admin.statusConfirmed': 'Confirmado',
    'admin.statusProcessing': 'Processando',
    'admin.statusShipped': 'Enviado',
    'admin.statusDelivered': 'Entregue',
    'admin.statusCancelled': 'Cancelado',
    'admin.statusCold': 'Frio',
    'admin.statusWarm': 'Morno',
    'admin.statusHot': 'Quente',
    'admin.statusConverted': 'Convertido',

    // Admin Products
    'admin.productsTitle': 'Produtos',
    'admin.productsSubtitle': 'Gerencie seu catálogo de produtos',
    'admin.newProduct': 'Novo Produto',
    'admin.editProduct': 'Editar Produto',
    'admin.productData': 'Preencha os dados do produto',
    'admin.searchProducts': 'Buscar produtos...',
    'admin.noProducts': 'Nenhum produto',
    'admin.productName': 'Nome *',
    'admin.category': 'Categoria',
    'admin.selectCategory': 'Selecionar categoria',
    'admin.description': 'Descrição',
    'admin.descriptionPlaceholder': 'Descrição do produto...',
    'admin.pricePYG': 'Preço (PYG) *',
    'admin.wholesalePrice': 'Preço Atacado',
    'admin.stock': 'Estoque',
    'admin.sizes': 'Variantes (separados por vírgula)',
    'admin.colors': 'Cores (separadas por vírgula)',
    'admin.active': 'Ativo',
    'admin.featured': 'Destaque',
    'admin.info': 'Informação',
    'admin.images': 'Imagens',
    'admin.video': 'Vídeo',
    'admin.productVideo': 'Vídeo do Produto',
    'admin.videoDesc': 'Faça upload de um vídeo de até 100MB (MP4, MOV, WebM). Será exibido na página do produto.',
    'admin.cancel': 'Cancelar',
    'admin.save': 'Salvar',
    'admin.create': 'Criar',
    'admin.edit': 'Editar',
    'admin.delete': 'Excluir',
    'admin.confirmDelete': 'Tem certeza que deseja excluir este produto?',
    'admin.productDeleted': 'Produto excluído',
    'admin.productUpdated': 'Produto atualizado',
    'admin.productCreated': 'Produto criado',
    'admin.couldNotDelete': 'Não foi possível excluir',
    'admin.couldNotSave': 'Não foi possível salvar',
    'admin.wholesale': 'Atacado',
    'admin.units': 'unidades',
    'admin.inactive': 'Inativo',

    // Admin Orders
    'admin.ordersTitle': 'Pedidos',
    'admin.ordersSubtitle': 'Gerencie os pedidos da sua loja',
    'admin.searchOrders': 'Buscar por número, nome ou email...',
    'admin.filterByStatus': 'Filtrar por status',
    'admin.all': 'Todos',
    'admin.order': 'Pedido',
    'admin.client': 'Cliente',
    'admin.status': 'Status',
    'admin.total': 'Total',
    'admin.date': 'Data',
    'admin.statusUpdated': 'Status atualizado',
    'admin.couldNotUpdate': 'Não foi possível atualizar',
    'admin.customerInfo': 'Cliente',
    'admin.shippingAddress': 'Endereço de Envio',
    'admin.tracking': 'Rastreamento',
    'admin.trackingNumber': 'Número de rastreamento',
    'admin.trackingAdded': 'Número de rastreamento adicionado',
    'admin.orderProducts': 'Produtos',
    'admin.size': 'Variante',
    'admin.subtotal': 'Subtotal',
    'admin.shipping': 'Frete',

    // Admin Layout
    'admin.backToStore': 'Voltar à loja',
    'admin.categories': 'Categorias',
    'admin.subcategories': 'Subcategorias',
    'admin.pages': 'Páginas',
    'admin.crmKanban': 'CRM Kanban',
    'admin.leads': 'Leads',
    'admin.socialPlanner': 'Planner Social',
    'admin.campaigns': 'Campanhas',
    'admin.credentials': 'Credenciais',
    'admin.reports': 'Relatórios',
    'admin.settings': 'Configuração',
    'admin.marketplaces': 'Marketplaces',
    'admin.signOut': 'Sair',
    'admin.mkConnections': 'Conexões',
    'admin.mkCatalog': 'Catálogo',
    'admin.mkOrders': 'Pedidos',
    'admin.mkStock': 'Estoque',
    'admin.mkMessages': 'Mensagens',
    'admin.mkPostSale': 'Automação Pós-Venda',
    'admin.mkAnalytics': 'Analytics',
    'admin.mkAutomations': 'Automações (n8n/Make/FiqOn)',
    'admin.mkLogs': 'Logs',

    // Categories
    'admin.categoriesTitle': 'Categorias',
    'admin.categoriesSubtitle': 'Organize seus produtos em categorias',
    'admin.newCategory': 'Nova Categoria',
    'admin.editCategory': 'Editar Categoria',
    'admin.categoryName': 'Nome',
    'admin.categorySlug': 'Slug',
    'admin.categoryDesc': 'Descrição',
    'admin.categoryDescPlaceholder': 'Descrição da categoria',
    'admin.categoryImageUrl': 'URL da Imagem',
    'admin.noCategories': 'Nenhuma categoria',
    'admin.categoryDeleted': 'Categoria excluída',
    'admin.categoryUpdated': 'Categoria atualizada',
    'admin.categoryCreated': 'Categoria criada',
    'admin.confirmDeleteCategory': 'Excluir esta categoria?',

    // Subcategories
    'admin.subcategoriesTitle': 'Subcategorias',
    'admin.subcategoriesSubtitle': 'Organize produtos dentro de categorias',
    'admin.newSubcategory': 'Nova Subcategoria',
    'admin.editSubcategory': 'Editar Subcategoria',
    'admin.parentCategory': 'Categoria pai',
    'admin.selectParentCategory': 'Selecionar categoria',
    'admin.noSubcategories': 'Nenhuma subcategoria',
    'admin.subcategoryDeleted': 'Subcategoria excluída',
    'admin.subcategoryUpdated': 'Subcategoria atualizada',
    'admin.subcategoryCreated': 'Subcategoria criada',
    'admin.confirmDeleteSubcategory': 'Excluir esta subcategoria?',

    // Customers
    'admin.customersTitle': 'Clientes',
    'admin.customersSubtitle': 'Gerencie as informações dos seus clientes',
    'admin.searchCustomers': 'Buscar clientes...',
    'admin.noCustomers': 'Nenhum cliente registrado',
    'admin.customerColumn': 'Cliente',
    'admin.contactColumn': 'Contato',
    'admin.cityColumn': 'Cidade',
    'admin.typeColumn': 'Tipo',
    'admin.registrationColumn': 'Registro',
    'admin.wholesaleType': 'Atacadista',
    'admin.retailType': 'Varejista',
    'admin.noName': 'Sem nome',

    // Leads
    'admin.leadsTitle': 'Leads',
    'admin.leadsSubtitle': 'Gerencie os leads do chatbot e formulários',
    'admin.searchLeads': 'Buscar leads...',
    'admin.noLeadsEmpty': 'Não há leads',
    'admin.leadColumn': 'Lead',
    'admin.contactLeadColumn': 'Contato',
    'admin.sourceColumn': 'Fonte',
    'admin.scoreColumn': 'Score',
    'admin.statusColumn': 'Status',
    'admin.dateColumn': 'Data',
    'admin.leadStatusUpdated': 'Status atualizado',

    // Settings
    'admin.settingsTitle': 'Configuração',
    'admin.settingsSubtitle': 'Gerencie a configuração da sua loja',
    'admin.tabStore': 'Loja',
    'admin.tabPayments': 'Pagamentos',
    'admin.tabWhatsApp': 'WhatsApp',
    'admin.tabApi': 'API Keys',
    'admin.storeInfo': 'Informações da Loja',
    'admin.storeInfoDesc': 'Configuração geral da sua loja',
    'admin.storeName': 'Nome da Loja',
    'admin.contactEmail': 'Email de Contato',
    'admin.phoneLabel': 'Telefone',
    'admin.freeShippingFrom': 'Frete grátis a partir de (PYG)',
    'admin.settingsSaved': 'Configuração salva',
    'admin.settingsError': 'Não foi possível salvar',
    'admin.stripeConfig': 'Configuração do Stripe',
    'admin.stripeConfigDesc': 'Configure sua integração com Stripe para processar pagamentos',
    'admin.important': 'Importante',
    'admin.stripeNote': 'Para ativar pagamentos com cartão, configure suas chaves de API do Stripe.',
    'admin.enableStripe': 'Habilitar Stripe',
    'admin.enableStripeDesc': 'Ative para processar pagamentos com cartão',
    'admin.publishableKey': 'Publishable Key (pk_...)',
    'admin.publicKeyNote': 'Esta chave é pública e usada no frontend',
    'admin.secretKey': 'Secret Key (sk_...)',
    'admin.secretKeyNote': 'Esta chave é privada e usada apenas no servidor',
    'admin.webhookSecret': 'Webhook Secret (whsec_...)',
    'admin.webhookSecretNote': 'Para verificar os webhooks do Stripe',
    'admin.whatsappConfig': 'Configuração do WhatsApp',
    'admin.whatsappConfigDesc': 'Configure a integração com WhatsApp Business API para notificações',
    'admin.whatsappNote': 'Para ativar notificações por WhatsApp, configure sua conta de WhatsApp Business API.',
    'admin.enableWhatsApp': 'Habilitar WhatsApp',
    'admin.enableWhatsAppDesc': 'Ative para enviar notificações de pedidos por WhatsApp',
    'admin.accessToken': 'Access Token',
    'admin.accessTokenNote': 'Token de acesso permanente do seu app Meta',
    'admin.phoneNumberId': 'Phone Number ID',
    'admin.phoneNumberIdNote': 'ID do número de telefone do WhatsApp Business',
    'admin.adminPhone': 'Número do Admin (para notificações)',
    'admin.adminPhoneNote': 'Número que receberá as notificações (formato: código país + número, sem +)',
    'admin.apiKeysTitle': 'API Keys & Integrações',
    'admin.apiKeysDesc': 'Gerencie as chaves de API para serviços externos',
    'admin.comingSoon': 'Em breve',
    'admin.comingSoonDesc': 'Esta seção permitirá configurar integrações com outros serviços.',

    // Reports
    'admin.reportsTitle': 'Relatórios',
    'admin.reportsSubtitle': 'Análise de vendas e desempenho',
    'admin.totalRevenueReport': 'Receita Total',
    'admin.totalOrdersReport': 'Total Pedidos',
    'admin.avgTicket': 'Ticket Médio',
    'admin.topProducts': 'Produtos Mais Vendidos',
    'admin.topProductsDesc': 'Top 5 produtos por receita',
    'admin.noSalesData': 'Sem dados de vendas',
    'admin.ordersByStatusReport': 'Pedidos por Status',
    'admin.orderDistribution': 'Distribuição atual de pedidos',
    'admin.noOrdersReport': 'Sem pedidos',
    'admin.unitsLabel': 'unidades',

    // CRM Kanban
    'admin.crmTitle': 'CRM Kanban',
    'admin.crmSubtitle': 'Pipeline de leads com drag & drop e IA',
    'admin.classifyAI': 'Classificar com IA',
    'admin.newLead': 'Novo Lead',
    'admin.nameLabel': 'Nome',
    'admin.emailLabel': 'Email',
    'admin.phoneFormLabel': 'Telefone',
    'admin.messageLabel': 'Mensagem',
    'admin.createLead': 'Criar',
    'admin.leadUpdated': 'Lead atualizado',
    'admin.leadCreated': 'Lead criado',
    'admin.aiClassifyDone': 'Classificação IA completada',
    'admin.leadsUpdated': 'leads atualizados',
    'admin.aiUnavailable': 'IA não disponível',
    'admin.configureAI': 'Configure a função de IA',
    'admin.aiResponseGenerated': 'Resposta IA gerada',
    'admin.aiResponseTitle': '🤖 Resposta IA Gerada',
    'admin.recommendedChannel': 'Canal recomendado',
    'admin.actionSuggestion': 'Sugestão de ação',
    'admin.messageForLead': 'Mensagem para o lead',
    'admin.close': 'Fechar',
    'admin.dragLeadsHere': 'Arraste leads aqui',
    'admin.couldNotGenerate': 'Não foi possível gerar resposta',

    // Social Planner
    'admin.socialTitle': 'Planner Social',
    'admin.socialSubtitle': 'Calendário de publicações em redes sociais',
    'admin.newPost': 'Novo Post',
    'admin.schedulePost': 'Agendar Post',
    'admin.platformLabel': 'Plataforma',
    'admin.contentLabel': 'Conteúdo',
    'admin.contentPlaceholder': 'Texto do post...',
    'admin.mediaLabel': 'Mídia (imagens/vídeos)',
    'admin.uploadFiles': 'Subir arquivos',
    'admin.maxFiles': 'Máximo 10 arquivos',
    'admin.dateTimeLabel': 'Data e hora',
    'admin.hashtagsLabel': 'Hashtags (separadas por vírgula)',
    'admin.schedule': 'Agendar',
    'admin.uploading': 'Subindo...',
    'admin.postScheduled': 'Post agendado',
    'admin.upcomingPosts': 'Próximas Publicações',
    'admin.noPostsMonth': 'Não há posts agendados este mês',
    'admin.noContent': 'Sem conteúdo',
    'admin.weekDays': 'Dom,Seg,Ter,Qua,Qui,Sex,Sáb',
    'admin.more': 'mais',

    // Campaigns
    'admin.campaignsTitle': 'Campanhas',
    'admin.campaignsSubtitle': 'Gerencie campanhas de ads em múltiplas plataformas',
    'admin.newCampaign': 'Nova Campanha',
    'admin.editCampaign': 'Editar Campanha',
    'admin.campaignName': 'Nome',
    'admin.campaignPlatform': 'Plataforma',
    'admin.campaignType': 'Tipo',
    'admin.campaignBudget': 'Orçamento (USD)',
    'admin.campaignBudgetType': 'Tipo de orçamento',
    'admin.budgetDaily': 'Diário',
    'admin.budgetLifetime': 'Total',
    'admin.campaignStart': 'Início',
    'admin.campaignEnd': 'Fim',
    'admin.campaignNotes': 'Notas',
    'admin.noCampaigns': 'Não há campanhas',
    'admin.campaignDeleted': 'Campanha excluída',
    'admin.campaignUpdated': 'Campanha atualizada',
    'admin.campaignCreated': 'Campanha criada',
    'admin.confirmDeleteCampaign': 'Excluir esta campanha?',
    'admin.activate': 'Ativar',
    'admin.pause': 'Pausar',
    'admin.reactivate': 'Reativar',
    'admin.archive': 'Arquivar',
    'admin.budgetColumn': 'Orçamento',
    'admin.periodColumn': 'Período',
    'admin.perDay': 'dia',
    'admin.perTotal': 'total',
    'admin.typeAwareness': 'Reconhecimento',
    'admin.typeTraffic': 'Tráfego',
    'admin.typeConversion': 'Conversão',
    'admin.typeEngagement': 'Interação',

    // API Credentials
    'admin.apiCredTitle': 'API & Credenciais',
    'admin.apiCredSubtitle': 'Gerencie chaves de API, tokens e webhooks',
    'admin.newCredential': 'Nova Credencial',
    'admin.editCredential': 'Editar Credencial',
    'admin.credPlatform': 'Plataforma',
    'admin.credType': 'Tipo',
    'admin.credName': 'Nome',
    'admin.credValue': 'Valor',
    'admin.credActive': 'Ativa',
    'admin.credInactive': 'Inativa',
    'admin.noCredentials': 'Nenhuma credencial configurada',
    'admin.credentialDeleted': 'Credencial excluída',
    'admin.credentialUpdated': 'Credencial atualizada',
    'admin.credentialCreated': 'Credencial criada',
    'admin.confirmDeleteCredential': 'Excluir esta credencial?',
    'admin.securityTitle': 'Segurança',
    'admin.securityNote': 'As credenciais estão protegidas e visíveis apenas para administradores. Nunca compartilhe estas chaves publicamente.',

    // Pages CMS
    'admin.pagesTitle': 'Páginas',
    'admin.pagesSubtitle': 'Crie e gerencie páginas personalizadas',
    'admin.newPage': 'Nova Página',
    'admin.editPage': 'Editar Página',
    'admin.pageTitle': 'Título',
    'admin.pageSlug': 'Slug',
    'admin.pageContent': 'Conteúdo',
    'admin.metaTitle': 'Meta Título (SEO)',
    'admin.metaTitlePlaceholder': 'Título para buscadores',
    'admin.metaDesc': 'Meta Descrição (SEO)',
    'admin.metaDescPlaceholder': 'Descrição para buscadores',
    'admin.publishedLabel': 'Publicada',
    'admin.draftLabel': 'Rascunho',
    'admin.noPages': 'Não há páginas',
    'admin.pageDeleted': 'Página excluída',
    'admin.pageUpdated': 'Página atualizada',
    'admin.pageCreated': 'Página criada',
    'admin.confirmDeletePage': 'Excluir esta página?',
    'admin.pageColumn': 'Página',
    'admin.slugColumn': 'Slug',
    'admin.statusPageColumn': 'Status',
    'admin.datePageColumn': 'Data',
    'admin.search': 'Buscar...',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Site fixado em português brasileiro - multilíngue removido
  const language: Language = 'pt';
  const setLanguage = useCallback((_lang: Language) => {
    // no-op: multilíngue removido
  }, []);

  const t = useCallback(
    (key: string) => translations['pt'][key] || key,
    []
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
